thisislist=["Apple","Orange","Cherry"]
thisistuple=("Apple","Orange","Cherry")
thisisset={"Apple","Orange","Cherry"}
print(len(thisislist))
print(len(thisistuple))
print(len(thisisset))
thisisset.add("mango")
print(thisisset)
thisislist.append("mango")
print(thisislist)
